/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsBox {
    }
}
declare global {
    interface HTMLDsBoxElement extends Components.DsBox, HTMLStencilElement {
    }
    var HTMLDsBoxElement: {
        prototype: HTMLDsBoxElement;
        new (): HTMLDsBoxElement;
    };
    interface HTMLElementTagNameMap {
        "ds-box": HTMLDsBoxElement;
    }
}
declare namespace LocalJSX {
    interface DsBox {
    }
    interface IntrinsicElements {
        "ds-box": DsBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-box": LocalJSX.DsBox & JSXBase.HTMLAttributes<HTMLDsBoxElement>;
        }
    }
}
